### ISSUE TITLE
What is BasePlayer?

### ISSUE THREAD

**Issue by n1lsik** [RequiChan/ExternalCounterstrike#1]
Hi. I try to use this code, but i get error related "BasePlayer". Please, help.

**Comment by RequiDev** [comment]
BasePlayer is a class for easily reading data If a player in csgo. What exactly is the error you are getting?

**Comment by full-screen** [comment]
don't have file BaseEntity.cs, pls add :+1:

**Comment by RequiDev** [comment]
https://github.com/RequiChan/ExternalCounterstrike/blob/master/ExternalCounterstrike/CSGO/BasePlayer.cs

**Comment by n1lsik** [comment]
Thanks!
